import Head from "next/head";
import Image from "next/image";
import { Loading } from "./Loading";
import { ToastContainer } from "react-toastify";
import { Header } from "./Header";

import "react-toastify/dist/ReactToastify.css";

interface LayoutProps {
  children: React.ReactNode;
  zoomLevel?: number; // Torna zoomLevel opcional
}

export function Layout({ children, zoomLevel = 1 }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Chá de Bebe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/baby-elephant.png" />
      </Head>
      <Header />
      <main
        id="main-content"
        className="flex flex-col w-full min-h-[calc(100vh-112px)] relative scrollbar-thin scrollbar-track-zinc-50 scrollbar-thumb-zinc-900"
      >
        {children}

        {/* Imagem de fundo */}
        <div className="absolute top-0 left-0 w-full h-full z-0">
          <Image
            priority
            alt="fundo elefante"
            src="/balao.png" // Caminho para a imagem
            layout="fill"
            objectFit="cover"
            objectPosition="center"
            className="z-0"
            quality={100} // Configura a qualidade para o máximo
            unoptimized // Desativa otimizações automáticas do Next.js
          />
        </div>
      </main>
      <Loading />
      <ToastContainer
        position="bottom-left"
        autoClose={2000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="dark"
      />
    </>
  );
}